#!/bin/bash
#
# Run the test suite when the test file changes.

if ! command -v inotifywait >/dev/null 2>&1 ; then
  echo "inotifywait executable not found in path!"
  exit 1
fi

inotifywait -r -e close_write -m .. |
while read -r directory events filename; do

  if [[ "$filename" == "test_all.sh" ]] || [[ "$filename" == "bash_describe" ]] ; then
    clear
    echo "---"
    ../bash_describe
  fi
done
